export const FETCH_MENU_REQUEST = "FETCH_MENU_REQUEST";
export const FETCH_MENU_SUCCESS = "FETCH_MENU_SUCCESS";
export const FETCH_MENU_ERROR = "FETCH_MENU_ERROR";

export const REMOVE_MENU_ITEM = "REMOVE_MENU_ITEM";
export const ADD_MENU_ITEM = "ADD_MENU_ITEM";